### ISSUE TITLE
How to use `introspection-uri`  in the sample authorization server? 

### ISSUE THREAD

**Issue by rrigoni** [marcosbarbero/spring-boot2-oauth2-opaque-token#1]
The endpoint `/profile/me`  it is a kind of token introspection, how to get this authorization server working with the `introspection-uri` in the `opaque-token` configuration in a resource server as follow?

The exposed endpoints are `/oauth/token_key`, `/oauth/check_token` and `/oauth/token` (to generate the token). Is the *introspection* endpoint the `/oauth/check_token`?

```
security:
  oauth2:
    resourceserver:
      opaque-token:
        introspection-uri: https://idp.example.com/introspect
        client-id: client
        client-secret: secret
```
